version: '3.8'

services:
  backend:
    build: ./backend
    container_name: english-backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - english-network
    # Không expose port ra ngoài, chỉ trong network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: english-frontend
    restart: always
    ports:
      - "8080:80"  # Map to 8080 để tránh conflict với nginx chính
    depends_on:
      - backend
    networks:
      - english-network

networks:
  english-network:
    driver: bridge
