cat > docker-compose.yml << 'EOF'
version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - mynet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - mynet

networks:
  mynet:
EOF
