version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    # Bỏ volumes trong production để tránh lỗi
    # volumes:
    #   - ./backend:/app
    restart: always
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
